#!/usr/bin/env python3
"""
Send daily email report for nanolife autonomous work.
Triggered by cron or called manually.
"""
import os
import json
from pathlib import Path
from datetime import datetime
import subprocess

PROJECT_ROOT = Path(__file__).parent
LOGS_DIR = PROJECT_ROOT / "autonomous_logs"

def get_latest_report():
    """Find the most recent report markdown file."""
    reports = sorted(LOGS_DIR.glob("report_cycle*.md"))
    if not reports:
        return None
    return reports[-1]

def get_latest_worker_log():
    """Find the most recent worker log."""
    logs = sorted(LOGS_DIR.glob("worker_*.log"))
    if not logs:
        return None
    return logs[-1]

def send_email_via_nebula(subject: str, body: str, recipient: str):
    """Send email using Nebula's email system via environment."""
    # This will be called by the Nebula runtime which has access to email tools
    # For now, just write to a file that the orchestrator can pick up
    email_request = {
        "to": recipient,
        "subject": subject,
        "body": body,
        "timestamp": datetime.now().isoformat()
    }
    
    outbox = LOGS_DIR / "email_outbox.json"
    with open(outbox, 'w') as f:
        json.dump(email_request, f, indent=2)
    
    print(f"Email queued: {subject}")
    return outbox

def main():
    # Get latest report
    report_file = get_latest_report()
    if not report_file:
        print("No reports found yet")
        return
    
    with open(report_file) as f:
        report_content = f.read()
    
    # Get last 50 lines of worker log for diagnostics
    log_file = get_latest_worker_log()
    log_tail = ""
    if log_file:
        with open(log_file) as f:
            lines = f.readlines()
            log_tail = "".join(lines[-50:])
    
    # Build email
    subject = f"nanolife Daily Report — {datetime.now().strftime('%Y-%m-%d')}"
    body = f"""{report_content}

---

## Recent Activity Log
```
{log_tail}
```

---
*Generated by nanolife autonomous worker*
"""
    
    # Send via Nebula
    recipient = os.getenv("REPORT_EMAIL", "cris@thelifesim.com")
    outbox_file = send_email_via_nebula(subject, body, recipient)
    
    print(f"Report email prepared: {outbox_file}")

if __name__ == "__main__":
    main()
